{
 "title": "API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP average duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_seconds_sum[5m]) / rate(http_requests_seconds_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Calculator Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(errors_calculator_total[5m])"
    }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_sum1n", "legendFormat": "Sum1n" },
    { "expr": "last_fibo", "legendFormat": "Fibo" },
    { "expr": "list_size", "legendFormat": "List size" },
    { "expr": "last_calculator", "legendFormat": "Calculator" }
   ]
  }
 ]
}